#                       Made by
#   ██████╗██████╗  █████╗  ██████╗ ██╗   ██╗███████╗
#  ██╔════╝██╔══██╗██╔══██╗██╔════╝ ██║   ██║██╔════╝
#  ██║     ██████╔╝███████║██║  ███╗██║   ██║███████╗
#  ██║     ██╔══██╗██╔══██║██║   ██║██║   ██║╚════██║
#  ╚██████╗██║  ██║██║  ██║╚██████╔╝╚██████╔╝███████║
#   ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚══════╝

settings:
  
  # Gebe deine BungeeCord IP ein.
  proxyIP: 127.0.0.1
  
  # Gebe die Kick Nachricht ein.
  playerKickMessage: '&cBitte Joine über die Domain'